markdown:         rdiscount
pygments:         true
paginate:         4

title:            Z'S 杂货铺
url:              http://alexzlj.github.com
feed:             /atom.xml
author:
    name:         ZLJ
    email:        alexzlj@gmail.com
description:      "一个爱折腾、拧巴的人"

about: 			  "一个爱折腾、拧巴的人"

follow:
    github:       https://github.com/alexzlj
    twitter:      http://weibo.com/u/1960033953?wvr=4&lf=reg
description:      "记录&思考的地方 "


style: 			  /css/style.css
blogName: 		  Z'S 杂货铺
blogDesc: 		  记录&思考&分享
